### ISSUE TITLE
uninitialized constant MongoDB::MongoClient

### ISSUE THREAD

**Issue by runningman84** [sensu-plugins/sensu-plugins-mongodb#3] opened 2015-03-27 08:38 UTC
This script does not work anymore using the latest mongo gem:

```
root@ip-172-31-25-141:/etc/sensu/plugins# /opt/sensu/embedded/bin/ruby mongodb-metrics.rb 
Check failed to run: uninitialized constant MongoDB::MongoClient, ["mongodb-metrics.rb:68:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]
root@ip-172-31-25-141:/etc/sensu/plugins# /opt/sensu/embedded/bin/gem list

*** LOCAL GEMS ***

amq-protocol (1.9.2)
amqp (1.5.0)
async_sinatra (1.0.0)
bigdecimal (1.2.0)
bson (3.0.0, 1.12.0)
bson_ext (1.12.0)
childprocess (0.5.3)
daemons (1.2.1)
domain_name (0.5.23)
em-redis-unified (0.6.0)
em-worker (0.0.2)
eventmachine (1.0.3)
ffi (1.9.8)
http-cookie (1.0.2)
io-console (0.4.2)
ipaddress (0.8.0)
json (1.7.7)
mime-types (2.4.3)
minitest (4.3.2)
mixlib-cli (1.5.0)
mixlib-config (2.1.0)
mixlib-log (1.6.0)
mixlib-shellout (2.0.1)
mongo (2.0.1)
multi_json (1.11.0)
netrc (0.10.3)
ohai (6.16.0)
psych (2.0.0)
rack (1.6.0)
rack-protection (1.5.3)
rake (0.9.6)
rdoc (4.0.0)
rest-client (1.8.0)
sensu (0.17.0)
sensu-em (2.4.1)
sensu-extension (1.1.2)
sensu-extensions (1.2.0)
sensu-logger (1.0.0)
sensu-plugin (1.1.0)
sensu-settings (1.3.0)
sensu-spawn (1.1.0)
sensu-transport (2.4.0)
sinatra (1.3.5)
systemu (2.6.4, 2.5.2)
test-unit (2.0.0.0)
thin (1.5.0)
tilt (1.4.1)
unf (0.1.4)
unf_ext (0.0.6)
uuidtools (2.1.4)
yajl-ruby (1.2.1)

**Comment by luisdalves** [comment] 2015-05-13 14:34
I have the same issue, I think this is caused by ruby 2.0 and latest mongo-ruby-driver, there is changes on methods so that's the problem

**Comment by mattyjones** [comment] 2015-05-14 01:30
We can always pin the the earlier version of the gem as a quick fix and then make the necessary changes in the plugins to ensure they work.

**Comment by sge-babrams** [comment] 2015-07-31 02:35
@mattyjones PR to pin versions: https://github.com/sensu-plugins/sensu-plugins-mongodb/pull/7

**Comment by JonathanHuot** [comment] 2015-11-25 20:37
Actually, all 1.x versions of gem mongo are working. I've tested mongo 1.12.4 and it worked fine. Do you have a way to change dependency to <2.0 ? or ==1.* ?

**Comment by eheydrick** [comment] 2015-11-25 20:57
I'd prefer to pin to specific versions so we control exactly what gets installed. The 0.0.7 release pins mongo to 1.12.3. We can certainly update the pin to 1.12.4 and release a new version. It would also be nice if the plugin was updated to work with 2.x.

**Comment by eheydrick** [comment] 2015-12-02 00:50
Is this still any issue with the latest release?

**Comment by JonathanHuot** [comment] 2015-12-04 10:59
I tested with latest version and it is still an issue.

**Comment by eheydrick** [comment] 2015-12-04 19:39
Thanks for checking. The plugin will need to be updated to work with 2.0 as it's a complete rewrite and not backwards compatible. I'm going to close this and we can open a new issue for 2.0.

**Closed by eheydrick** 2015-12-04 19:39 UTC
Labels: Investigation Required
